[package]
name = "presence_java_ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "presence_java"
crate-type = ["cdylib"]

[dependencies]
presence_core = { path = "../presence_core" }
jni = "0.21.1"
log = "0.3.0"
android_logger = "0.3.0"
env_logger = "0.11.3"