/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_nearby_presence_Presence */

#ifndef _Included_com_google_nearby_presence_Presence
#define _Included_com_google_nearby_presence_Presence
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_nearby_presence_Presence
 * Method:    newPresence
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_google_nearby_presence_Presence_newPresence
  (JNIEnv *, jclass);

/*
 * Class:     com_google_nearby_presence_Presence
 * Method:    setRequest
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_google_nearby_presence_Presence_setRequest
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_google_nearby_presence_Presence
 * Method:    start
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_google_nearby_presence_Presence_start
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_google_nearby_presence_Presence
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_google_nearby_presence_Presence_stop
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
