[package]
name = "system_api_java_ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
system_api_core = { path = "../core" }
log = "0.4.20"
jni = "0.21.1"