plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.google.nearby.presence_test'
    compileSdk 34

    defaultConfig {
        applicationId "com.google.nearby.presence_test"
        minSdk 30
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }

        project.logger.info("Set ANDROID_HOME for NDK: ${System.env.ANDROID_HOME}")
        externalNativeBuild {
            cmake {
                targets "presence_android"
                arguments.add("-DANDROID_HOME_DIR=${System.env.ANDROID_HOME}")
            }
        }
        ndk { abiFilters 'arm64-v8a' }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        compose true
    }
    packaging {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }
}

dependencies {
    // implementation fileTree('libs') { include '*.jar' }
    implementation libs.androidx.annotation.jvm
}