/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestDiscoveryResult */

#ifndef _Included_TestDiscoveryResult
#define _Included_TestDiscoveryResult
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestDiscoveryResult
 * Method:    testDiscoveryResult
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_TestDiscoveryResult_testDiscoveryResult
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
