[package]
name = "presence_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
event_poller = { path = "../../event_poller" }
ble = { path = "../../ble" }
tokio = { version = "1.36.0", features = ["sync", "rt-multi-thread", "macros"] }
log = "0.4.22"
futures = "0.3.31"
np_adv = { git = "https://beto-core.googlesource.com/beto-core.git", branch = "main" }
jni = "0.21.1"


