[package]
name = "presence_java"
version = "0.1.0"
edition = "2021"

[lib]
name = "presence_java"
crate-type = ["cdylib"]

[features]
mock = []

[dependencies]
presence_rust = { path = "../presence_rust" }
ble = { path = "../../ble" }
jni = "0.21.1"
log = "0.4.22"
android_logger = "0.14.1"
env_logger = "0.11.5"
