/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_nearby_test_Ble */

#ifndef _Included_com_google_nearby_test_Ble
#define _Included_com_google_nearby_test_Ble
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_nearby_test_Ble
 * Method:    newBle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_google_nearby_test_Ble_newBle
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
