/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_nearby_presence_engine_PresenceEngine */

#ifndef _Included_com_google_nearby_presence_engine_PresenceEngine
#define _Included_com_google_nearby_presence_engine_PresenceEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_nearby_presence_engine_PresenceEngine
 * Method:    PresenceEngineNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_google_nearby_presence_engine_PresenceEngine_PresenceEngineNew
  (JNIEnv *, jclass);

/*
 * Class:     com_google_nearby_presence_engine_PresenceEngine
 * Method:    PresenceEngineRun
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_google_nearby_presence_engine_PresenceEngine_PresenceEngineRun
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_google_nearby_presence_engine_PresenceEngine
 * Method:    PresenceEngineDebug
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_google_nearby_presence_engine_PresenceEngine_PresenceEngineDebug
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_google_nearby_presence_engine_PresenceEngine
 * Method:    PresenceEngineFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_google_nearby_presence_engine_PresenceEngine_PresenceEngineFree
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
