/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_nearby_presence_engine_Engine */

#ifndef _Included_com_google_nearby_presence_engine_Engine
#define _Included_com_google_nearby_presence_engine_Engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_nearby_presence_engine_Engine
 * Method:    start
 * Signature: (Lcom/google/nearby/presence/engine/Engine;)J
 */
JNIEXPORT jlong JNICALL Java_com_google_nearby_presence_engine_Engine_start
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_google_nearby_presence_engine_Engine
 * Method:    debug
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_google_nearby_presence_engine_Engine_debug
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_google_nearby_presence_engine_Engine
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_google_nearby_presence_engine_Engine_free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
