/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_nearby_ble_ScanResult */

#ifndef _Included_com_google_nearby_ble_ScanResult
#define _Included_com_google_nearby_ble_ScanResult
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_nearby_ble_ScanResult
 * Method:    toRustScanResult
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_google_nearby_ble_ScanResult_toRustScanResult
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
