/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_goog_nearby_presence_test_TestNdk */

#ifndef _Included_com_goog_nearby_presence_test_TestNdk
#define _Included_com_goog_nearby_presence_test_TestNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_goog_nearby_presence_test_TestNdk
 * Method:    newNdk
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_goog_nearby_presence_1test_TestNdk_newNdk
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
