/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_nearby_api_TestApi */

#ifndef _Included_com_google_nearby_api_TestApi
#define _Included_com_google_nearby_api_TestApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_nearby_api_TestApi
 * Method:    startScan
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_nearby_api_TestApi_startScan
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
