/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_nearby_ble_test_TestBleScanner */

#ifndef _Included_com_google_nearby_ble_test_TestBleScanner
#define _Included_com_google_nearby_ble_test_TestBleScanner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_nearby_ble_test_TestBleScanner
 * Method:    newTestBleScanner
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_google_nearby_ble_1test_TestBleScanner_newTestBleScanner
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
